# Generated by Django 5.2.7 on 2025-10-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_project_description_alter_project_budget_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('not-paid', 'Не оплачен'), ('pending', 'Ожидает оплаты')], default='not-paid', max_length=20, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'К выполнению'), ('inwork', 'В работе'), ('done', 'Завершён'), ('overdue', 'Просрочен'), ('paused', 'Приостановлен')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название проекта'),
        ),
    ]
