# Generated by Django 5.2.7 on 2025-10-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_project_options_project_client_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', 'position'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
