# Generated by Django 5.2.7 on 2025-10-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_project_options_project_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='position',
        ),
    ]
