# Generated by Django 5.2.7 on 2025-10-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_project_options_remove_project_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
    ]
