# Generated by Django 5.2.7 on 2025-10-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', 'order', 'id'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
