# Generated by Django 5.2.7 on 2025-10-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', 'order', 'id']},
        ),
    ]
