# Generated by Django 6.0.3 on 2026-03-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_client_remove_project_client_name_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
    ]
