# Generated by Django 6.0.3 on 2026-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('not_paid', 'Не оплачен'), ('pending', 'Ожидает оплаты')], default='not-paid', max_length=20, verbose_name='Оплата'),
        ),
    ]
