# Generated by Django 6.0.3 on 2026-03-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
