# Generated by Django 6.0.3 on 2026-03-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_project_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
