# Generated by Django 6.0.3 on 2026-04-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_estimate_estimateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
