# Generated by Django 6.0.3 on 2026-04-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_estimate_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.estimate', verbose_name='Основание (смета)'),
        ),
    ]
